/**
 * data.js — Scholarshipping scholarship database
 *
 * Real scholarships with verified metadata.
 * Always verify details at the official URL before applying.
 * Last updated: 2026-02-27
 *
 * Sources verified Feb 2026. Amounts, deadlines, and eligibility
 * requirements change annually — always confirm at the official URL.
 */

const SCHOLARSHIPS = [
  // ─────────────────────────────────────────────────────────────
  // LARGE NATIONAL / FLAGSHIP SCHOLARSHIPS
  // ─────────────────────────────────────────────────────────────
  {
    id: 1,
    name: "Gates Scholarship",
    organization: "Bill & Melinda Gates Foundation",
    amount: 50000,
    deadline_month: "September",
    renewable: true,
    type: "need-based",
    gpa_required: 3.3,
    essay_required: true,
    state: "National",
    year_eligible: "High School Senior",
    description: "Full scholarship covering unmet financial need for outstanding minority students in the US. Covers tuition, room & board, books, and personal expenses for 4+ years.",
    url: "https://www.thegatesscholarship.org",
    tags: ["minority", "need-based", "renewable", "first-generation", "full-ride"],
    likelihood: "low"
  },
  {
    id: 2,
    name: "Coca-Cola Scholars Program",
    organization: "Coca-Cola Scholars Foundation",
    amount: 20000,
    deadline_month: "October",
    renewable: false,
    type: "merit",
    gpa_required: 0,
    essay_required: true,
    state: "National",
    year_eligible: "High School Senior",
    description: "One of the most prestigious scholarships in the US, awarded to 150 high school seniors who demonstrate leadership and a commitment to service.",
    url: "https://www.coca-colascholarsfoundation.org",
    tags: ["leadership", "service", "prestigious", "merit"],
    likelihood: "low"
  },
  {
    id: 3,
    name: "Elks National Foundation Most Valuable Student",
    organization: "Elks National Foundation",
    amount: 30000,
    deadline_month: "November",
    renewable: true,
    type: "merit",
    gpa_required: 0,
    essay_required: true,
    state: "National",
    year_eligible: "High School Senior",
    description: "Awards 500 four-year scholarships to students who demonstrate leadership, scholarship, and financial need. Top 20 scholars receive $30,000; remaining 480 receive $4,000.",
    url: "https://www.elks.org/scholars/scholarships/mvs.cfm",
    tags: ["leadership", "merit", "renewable", "community"],
    likelihood: "medium"
  },
  {
    id: 4,
    name: "Jack Kent Cooke Foundation College Scholarship",
    organization: "Jack Kent Cooke Foundation",
    amount: 55000,
    deadline_month: "November",
    renewable: true,
    type: "need-based",
    gpa_required: 3.75,
    essay_required: true,
    state: "National",
    year_eligible: "High School Senior",
    description: "One of the largest scholarships for high-achieving students with financial need, covering up to $55,000 per year for four years. Family income must be under $95,000. Applied through Common App.",
    url: "https://www.jkcf.org/our-scholarships/college-scholarship-program/",
    tags: ["high-achieving", "need-based", "full-ride", "renewable"],
    likelihood: "low"
  },
  {
    id: 5,
    name: "National Merit Scholarship",
    organization: "National Merit Scholarship Corporation",
    amount: 2500,
    deadline_month: "October",
    renewable: false,
    type: "merit",
    gpa_required: 0,
    essay_required: false,
    state: "National",
    year_eligible: "High School Senior",
    description: "Awarded based on PSAT/NMSQT scores. About 7,500 National Merit Scholarships are awarded annually. Corporate-sponsored awards can be much higher.",
    url: "https://www.nationalmerit.org",
    tags: ["psat", "test-scores", "merit", "academic"],
    likelihood: "medium"
  },
  {
    id: 6,
    name: "Questbridge National College Match",
    organization: "QuestBridge",
    amount: 50000,
    deadline_month: "September",
    renewable: true,
    type: "need-based",
    gpa_required: 3.5,
    essay_required: true,
    state: "National",
    year_eligible: "High School Senior",
    description: "Connects high-achieving, low-income students with full four-year scholarships at 45+ partner colleges including Yale, Princeton, Stanford, and MIT.",
    url: "https://www.questbridge.org",
    tags: ["low-income", "elite-college", "full-ride", "renewable", "first-generation"],
    likelihood: "low"
  },
  {
    id: 7,
    name: "Dell Scholars Program",
    organization: "Michael & Susan Dell Foundation",
    amount: 20000,
    deadline_month: "February",
    renewable: true,
    type: "need-based",
    gpa_required: 2.4,
    essay_required: true,
    state: "National",
    year_eligible: "High School Senior",
    description: "Supports students who have overcome significant obstacles to prepare for college. Provides $20,000 over 6 years plus a laptop, Chegg textbook credits, and ongoing support resources. Must be enrolled in a Dell Foundation college readiness program.",
    url: "https://www.dellscholars.org/students/",
    tags: ["first-generation", "need-based", "renewable", "low-income", "resilience"],
    likelihood: "medium"
  },
  {
    id: 8,
    name: "Burger King Scholars Program (WHOPPER Award)",
    organization: "Burger King Foundation",
    amount: 60000,
    deadline_month: "December",
    renewable: false,
    type: "need-based",
    gpa_required: 0,
    essay_required: true,
    state: "National",
    year_eligible: "High School Senior",
    description: "Open to all graduating high school seniors, BK employees, and their families. The top WHOPPER Award gives $60,000; hundreds of $1,000–$10,000 awards also given.",
    url: "https://burgerking.scholarsapply.org",
    tags: ["need-based", "work-experience", "community-service", "open-to-all"],
    likelihood: "medium"
  },
  {
    id: 9,
    name: "Ron Brown Scholar Program",
    organization: "Ron Brown Scholar Program",
    amount: 40000,
    deadline_month: "December",
    renewable: true,
    type: "identity",
    gpa_required: 0,
    essay_required: true,
    state: "National",
    year_eligible: "High School Senior",
    description: "Awards 20 scholarships of $10,000/year for 4 years to academically talented African-American students who demonstrate financial need, exceptional leadership, and service. Final deadline December 1.",
    url: "https://ronbrown.org/ron-brown-scholarship/",
    tags: ["African-American", "leadership", "service", "renewable", "need-based"],
    likelihood: "low"
  },
  {
    id: 10,
    name: "Horatio Alger National Scholarship",
    organization: "Horatio Alger Association",
    amount: 25000,
    deadline_month: "March",
    renewable: false,
    type: "need-based",
    gpa_required: 2.0,
    essay_required: true,
    state: "National",
    year_eligible: "High School Senior",
    description: "Supports high school juniors (who apply the following year as seniors) who have faced adversity and demonstrated integrity. Minimum 2.0 GPA, family AGI under $100,000. Deadline March 1.",
    url: "https://scholars.horatioalger.org/scholarships/",
    tags: ["adversity", "resilience", "need-based", "community-service"],
    likelihood: "medium"
  },

  // ─────────────────────────────────────────────────────────────
  // STEM SCHOLARSHIPS
  // ─────────────────────────────────────────────────────────────
  {
    id: 11,
    name: "Barry Goldwater Scholarship",
    organization: "Barry Goldwater Scholarship and Excellence in Education Foundation",
    amount: 7500,
    deadline_month: "January",
    renewable: true,
    type: "stem",
    gpa_required: 3.0,
    essay_required: true,
    state: "National",
    year_eligible: "Undergraduate",
    description: "Premier undergraduate award for students intending to pursue research careers in natural sciences, mathematics, or engineering. Up to $7,500/year for 1–2 years.",
    url: "https://goldwaterscholarship.gov",
    tags: ["research", "STEM", "mathematics", "natural-sciences", "engineering"],
    likelihood: "low"
  },
  {
    id: 12,
    name: "Society of Women Engineers Scholarship",
    organization: "Society of Women Engineers (SWE)",
    amount: 17000,
    deadline_month: "February",
    renewable: true,
    type: "stem",
    gpa_required: 3.0,
    essay_required: true,
    state: "National",
    year_eligible: "Undergraduate",
    description: "SWE offers 260+ scholarships totaling $1M+ annually for women studying engineering and engineering technology. Awards range from $1,000 to $17,000.",
    url: "https://scholarships.swe.org",
    tags: ["women", "engineering", "STEM", "renewable"],
    likelihood: "medium"
  },
  {
    id: 13,
    name: "Regeneron ISEF (International Science and Engineering Fair)",
    organization: "Society for Science",
    amount: 75000,
    deadline_month: "Rolling",
    renewable: false,
    type: "stem",
    gpa_required: 0,
    essay_required: true,
    state: "National",
    year_eligible: "High School Senior",
    description: "World's largest pre-college STEM competition for grades 9-12. Finalists compete for nearly $9 million in awards including a $75,000 top scholarship. Students advance through local/regional fairs.",
    url: "https://www.societyforscience.org/isef/",
    tags: ["research", "science", "competition", "engineering", "innovation"],
    likelihood: "low"
  },
  {
    id: 14,
    name: "SMART Scholarship for Service Program",
    organization: "US Department of Defense",
    amount: 38000,
    deadline_month: "December",
    renewable: true,
    type: "stem",
    gpa_required: 3.0,
    essay_required: true,
    state: "National",
    year_eligible: "Undergraduate",
    description: "Full tuition plus a stipend for STEM students who commit to work for the Department of Defense after graduation. Includes full funding, health insurance, and a paid internship.",
    url: "https://www.smartscholarship.org",
    tags: ["DoD", "government", "STEM", "full-ride", "service-commitment"],
    likelihood: "medium"
  },
  {
    id: 15,
    name: "Google Generation Scholarship",
    organization: "Google",
    amount: 10000,
    deadline_month: "December",
    renewable: false,
    type: "stem",
    gpa_required: 3.2,
    essay_required: true,
    state: "National",
    year_eligible: "Undergraduate",
    description: "Supports students from underrepresented groups (women, Black, Hispanic, Indigenous, or students with disabilities) who are studying computer science or related fields.",
    url: "https://buildyourfuture.withgoogle.com/scholarships",
    tags: ["computer-science", "tech", "underrepresented", "diversity", "STEM"],
    likelihood: "medium"
  },
  {
    id: 16,
    name: "Microsoft Tuition Scholarship",
    organization: "Microsoft Corporation",
    amount: 10000,
    deadline_month: "February",
    renewable: false,
    type: "stem",
    gpa_required: 3.0,
    essay_required: true,
    state: "National",
    year_eligible: "Undergraduate",
    description: "For students studying computer science, computer engineering, or related STEM fields. Preference given to students with disabilities, women, and underrepresented minorities.",
    url: "https://careers.microsoft.com/us/en/usscholarship",
    tags: ["computer-science", "tech", "diversity", "STEM", "underrepresented"],
    likelihood: "medium"
  },
  {
    id: 17,
    name: "AFCEA STEM Scholarship",
    organization: "Armed Forces Communications and Electronics Association",
    amount: 5000,
    deadline_month: "February",
    renewable: false,
    type: "stem",
    gpa_required: 3.0,
    essay_required: false,
    state: "National",
    year_eligible: "Undergraduate",
    description: "Supports students studying STEM fields related to national security, communications, or electronics. Particularly available to veterans, active duty, and their family members.",
    url: "https://www.afcea.org/scholarships",
    tags: ["military", "STEM", "engineering", "veterans", "national-security"],
    likelihood: "medium"
  },
  {
    id: 18,
    name: "Regeneron Science Talent Search",
    organization: "Society for Science",
    amount: 250000,
    deadline_month: "November",
    renewable: false,
    type: "stem",
    gpa_required: 0,
    essay_required: true,
    state: "National",
    year_eligible: "High School Senior",
    description: "The nation's oldest and most prestigious science competition for high school seniors. Top prize is $250,000; 40 finalists each receive at least $25,000. Requires an original independent research paper submitted by November deadline.",
    url: "https://www.societyforscience.org/regeneron-sts/",
    tags: ["research", "science", "competition", "high-school", "prestigious"],
    likelihood: "low"
  },
  {
    id: 19,
    name: "American Chemical Society Scholars Program",
    organization: "American Chemical Society",
    amount: 5000,
    deadline_month: "March",
    renewable: true,
    type: "stem",
    gpa_required: 3.0,
    essay_required: true,
    state: "National",
    year_eligible: "Undergraduate",
    description: "Awarded to underrepresented minority students studying chemistry, biochemistry, chemical engineering, or a related field. Renewable for up to 4 years.",
    url: "https://www.acs.org/content/acs/en/funding/scholarships-fellowships/acs-scholars.html",
    tags: ["chemistry", "minority", "STEM", "renewable"],
    likelihood: "medium"
  },
  {
    id: 20,
    name: "National Space Club Keynote Scholar Award",
    organization: "National Space Club and Foundation",
    amount: 10000,
    deadline_month: "February",
    renewable: false,
    type: "stem",
    gpa_required: 0,
    essay_required: true,
    state: "National",
    year_eligible: "Undergraduate",
    description: "For a high school junior or senior or college student with a special aptitude for science and mathematics and a desire to pursue their studies toward a career in aerospace.",
    url: "https://www.spaceclub.org/scholarship/",
    tags: ["aerospace", "space", "science", "mathematics", "STEM"],
    likelihood: "low"
  },

  // ─────────────────────────────────────────────────────────────
  // IDENTITY-BASED SCHOLARSHIPS
  // ─────────────────────────────────────────────────────────────
  {
    id: 21,
    name: "UNCF (United Negro College Fund) Scholarship",
    organization: "United Negro College Fund",
    amount: 10000,
    deadline_month: "Rolling",
    renewable: true,
    type: "identity",
    gpa_required: 2.5,
    essay_required: true,
    state: "National",
    year_eligible: "Any",
    description: "UNCF administers over 400 scholarships and fellowships for African-American students. Most require enrollment at an HBCU or other accredited institution.",
    url: "https://uncf.org/scholarships",
    tags: ["African-American", "HBCU", "renewable", "need-based"],
    likelihood: "medium"
  },
  {
    id: 22,
    name: "Hispanic Scholarship Fund (HSF) General Scholarship",
    organization: "Hispanic Scholarship Fund",
    amount: 5000,
    deadline_month: "February",
    renewable: false,
    type: "identity",
    gpa_required: 3.0,
    essay_required: true,
    state: "National",
    year_eligible: "Any",
    description: "The nation's largest nonprofit supporting Hispanic higher education. Awards $500–$5,000 to students of Hispanic heritage based on merit and financial need. Selects 10,000 scholars annually. Must reapply each year.",
    url: "https://www.hsf.net/scholarship/",
    tags: ["Hispanic", "Latino", "merit", "need-based", "FAFSA"],
    likelihood: "medium"
  },
  {
    id: 23,
    name: "Point Foundation LGBTQ+ Flagship Scholarship",
    organization: "Point Foundation",
    amount: 10000,
    deadline_month: "November",
    renewable: true,
    type: "identity",
    gpa_required: 3.3,
    essay_required: true,
    state: "National",
    year_eligible: "Undergraduate",
    description: "The nation's largest scholarship fund for LGBTQ+ students. Average award $10,000/year for up to four years. Application opens September 10, closes November 20. Open to undocumented students.",
    url: "https://pointfoundation.org/scholarships/flagship",
    tags: ["LGBTQ+", "need-based", "community-leader", "renewable"],
    likelihood: "low"
  },
  {
    id: 24,
    name: "American Indian College Fund Full Circle Scholarship",
    organization: "American Indian College Fund",
    amount: 3000,
    deadline_month: "May",
    renewable: true,
    type: "identity",
    gpa_required: 2.0,
    essay_required: true,
    state: "National",
    year_eligible: "Any",
    description: "The nation's largest Native scholarship provider. Offers 300+ scholarships averaging $2,000–$3,000 for enrolled tribal members or descendants. Application opens February 1 each year; priority deadline May 31.",
    url: "https://collegefund.org/students/scholarships/",
    tags: ["Native-American", "Indigenous", "need-based", "renewable"],
    likelihood: "medium"
  },
  {
    id: 25,
    name: "Asian & Pacific Islander American Scholarship Fund",
    organization: "Asian & Pacific Islander American Scholarship Fund (APIASF)",
    amount: 20000,
    deadline_month: "January",
    renewable: true,
    type: "identity",
    gpa_required: 2.7,
    essay_required: true,
    state: "National",
    year_eligible: "Any",
    description: "Supports Asian and Pacific Islander American students with demonstrated financial need. Multiple award levels; larger awards for students at specific partner institutions.",
    url: "https://apiasf.org",
    tags: ["Asian-American", "Pacific-Islander", "need-based", "renewable"],
    likelihood: "medium"
  },
  {
    id: 26,
    name: "TheDream.US National Scholarship",
    organization: "TheDream.US",
    amount: 33000,
    deadline_month: "February",
    renewable: true,
    type: "identity",
    gpa_required: 2.5,
    essay_required: true,
    state: "National",
    year_eligible: "High School Senior",
    description: "For undocumented, DACA, or TPS students — the nation's largest college access program for immigrant students. Covers up to $33,000 over 4 years at nearly 80 Partner Colleges. Deadline February 28.",
    url: "https://www.thedream.us/scholarships/national-scholarship/",
    tags: ["undocumented", "DACA", "immigrant", "first-generation", "renewable"],
    likelihood: "medium"
  },
  {
    id: 27,
    name: "Disabled American Veterans (DAV) Scholarship",
    organization: "Disabled American Veterans Auxiliary",
    amount: 1500,
    deadline_month: "February",
    renewable: true,
    type: "identity",
    gpa_required: 0,
    essay_required: true,
    state: "National",
    year_eligible: "Any",
    description: "For members of the DAV Auxiliary or children and grandchildren of veterans who served in the US armed forces, especially during periods of war.",
    url: "https://www.davauxiliary.org/programs/scholarships/",
    tags: ["veterans", "military-family", "service", "renewable"],
    likelihood: "high"
  },
  {
    id: 28,
    name: "Jeannette Rankin Women's Scholarship",
    organization: "Jeannette Rankin Foundation",
    amount: 2500,
    deadline_month: "February",
    renewable: true,
    type: "identity",
    gpa_required: 0,
    essay_required: true,
    state: "National",
    year_eligible: "Undergraduate",
    description: "For low-income women age 35 and older (or 25+ in Montana, Georgia, or attending a Tribal College) pursuing vocational, associate, or bachelor's degrees. Up to $2,500 renewable for 5 years. Application opens November, closes February 13.",
    url: "https://rankinfoundation.org/national-scholar-grant/",
    tags: ["women", "non-traditional", "low-income", "adult-learner"],
    likelihood: "medium"
  },
  {
    id: 29,
    name: "National Federation of the Blind Scholarship",
    organization: "National Federation of the Blind",
    amount: 8000,
    deadline_month: "March",
    renewable: false,
    type: "identity",
    gpa_required: 0,
    essay_required: true,
    state: "National",
    year_eligible: "Any",
    description: "30 scholarships totaling $240,000+ for legally blind full-time students (must be 18+ by July 3). Finalists must attend the NFB National Convention in person. Deadline March 31.",
    url: "https://nfb.org/scholarships",
    tags: ["disability", "blind", "visual-impairment", "any-major"],
    likelihood: "medium"
  },
  {
    id: 30,
    name: "P.E.O. Program for Continuing Education",
    organization: "P.E.O. International",
    amount: 3000,
    deadline_month: "Rolling",
    renewable: false,
    type: "identity",
    gpa_required: 0,
    essay_required: true,
    state: "National",
    year_eligible: "Undergraduate",
    description: "For women in the US or Canada who need financial help to complete an undergraduate degree after an interruption of 24+ months. Applied for through local P.E.O. chapters.",
    url: "https://www.peointernational.org/about-peo-continuing-education-fund",
    tags: ["women", "non-traditional", "adult-learner", "re-entry"],
    likelihood: "high"
  },

  // ─────────────────────────────────────────────────────────────
  // FIELD-OF-STUDY SCHOLARSHIPS
  // ─────────────────────────────────────────────────────────────
  {
    id: 31,
    name: "American Medical Association Foundation Scholarship",
    organization: "AMA Foundation",
    amount: 10000,
    deadline_month: "April",
    renewable: false,
    type: "field-of-study",
    gpa_required: 0,
    essay_required: true,
    state: "National",
    year_eligible: "Undergraduate",
    description: "For medical students demonstrating financial need and a commitment to the advancement of medicine and public health. Requires AMA membership application.",
    url: "https://www.ama-assn.org/amaone/ama-foundation",
    tags: ["medicine", "pre-med", "healthcare", "need-based"],
    likelihood: "medium"
  },
  {
    id: 32,
    name: "American Bar Association Legal Opportunity Scholarship",
    organization: "American Bar Association",
    amount: 15000,
    deadline_month: "March",
    renewable: true,
    type: "field-of-study",
    gpa_required: 0,
    essay_required: true,
    state: "National",
    year_eligible: "Undergraduate",
    description: "For students from racial and ethnic minority groups who are entering law school. Provides $5,000/year for 3 years plus mentoring, networking, and professional development.",
    url: "https://www.americanbar.org/groups/diversity/racial_ethnic_diversity/initiatives_awards/legal_opportunity_scholarship/",
    tags: ["law", "pre-law", "minority", "renewable", "mentorship"],
    likelihood: "medium"
  },
  {
    id: 33,
    name: "TEACH Grant",
    organization: "US Department of Education",
    amount: 4000,
    deadline_month: "Rolling",
    renewable: true,
    type: "field-of-study",
    gpa_required: 3.25,
    essay_required: false,
    state: "National",
    year_eligible: "Undergraduate",
    description: "Annual grant of up to $4,000 for students planning to teach in high-need fields (e.g., math, science, foreign languages, special education) at low-income schools. Converts to an unsubsidized loan if 4-year service obligation is not fulfilled.",
    url: "https://studentaid.gov/understand-aid/types/grants/teach",
    tags: ["education", "teaching", "service-commitment", "high-need", "renewable"],
    likelihood: "high"
  },
  {
    id: 34,
    name: "National Press Foundation Scholarship",
    organization: "National Press Foundation",
    amount: 2000,
    deadline_month: "April",
    renewable: false,
    type: "field-of-study",
    gpa_required: 3.0,
    essay_required: true,
    state: "National",
    year_eligible: "Undergraduate",
    description: "For students pursuing careers in journalism. Requires demonstrated interest and experience in journalism through internships or campus media involvement.",
    url: "https://nationalpress.org/programs/scholarships/",
    tags: ["journalism", "media", "writing", "reporting"],
    likelihood: "medium"
  },
  {
    id: 35,
    name: "American Nurses Foundation Scholarship Program",
    organization: "American Nurses Foundation",
    amount: 5000,
    deadline_month: "June",
    renewable: false,
    type: "field-of-study",
    gpa_required: 3.0,
    essay_required: true,
    state: "National",
    year_eligible: "Undergraduate",
    description: "Multiple scholarships for students enrolled in accredited nursing programs. Includes awards specifically for underrepresented minorities and first-generation students.",
    url: "https://www.nursingworld.org/foundation/programs/scholarships/",
    tags: ["nursing", "healthcare", "minority", "first-generation"],
    likelihood: "medium"
  },
  {
    id: 36,
    name: "Association of Public Health Nurses Scholarship",
    organization: "Association of Public Health Nurses (APHN)",
    amount: 1500,
    deadline_month: "April",
    renewable: false,
    type: "field-of-study",
    gpa_required: 3.0,
    essay_required: true,
    state: "National",
    year_eligible: "Undergraduate",
    description: "For nursing students who demonstrate an interest in pursuing a career in public health nursing. Preference for financial need.",
    url: "https://www.aphnnursing.org/scholarships",
    tags: ["nursing", "public-health", "healthcare", "need-based"],
    likelihood: "high"
  },
  {
    id: 37,
    name: "American Institute of Certified Public Accountants (AICPA) Scholarship",
    organization: "AICPA Foundation",
    amount: 5000,
    deadline_month: "March",
    renewable: true,
    type: "field-of-study",
    gpa_required: 3.0,
    essay_required: false,
    state: "National",
    year_eligible: "Undergraduate",
    description: "For students pursuing accounting or related business degrees. Must be a student affiliate member of AICPA. Multiple award tracks including diversity-focused awards.",
    url: "https://www.aicpa.org/career/scholarships.html",
    tags: ["accounting", "business", "finance", "renewable"],
    likelihood: "medium"
  },
  {
    id: 38,
    name: "Rotary Foundation Global Grant Scholarship",
    organization: "Rotary International",
    amount: 30000,
    deadline_month: "Rolling",
    renewable: false,
    type: "field-of-study",
    gpa_required: 0,
    essay_required: true,
    state: "National",
    year_eligible: "Undergraduate",
    description: "For graduate-level study or vocational training that aligns with Rotary's areas of focus: peace, disease prevention, water, sanitation, maternal health, basic education, or economic development.",
    url: "https://www.rotary.org/en/our-programs/scholarships",
    tags: ["international", "peace", "service", "global", "vocational"],
    likelihood: "low"
  },
  {
    id: 39,
    name: "Veterinary Education Scholarship Program",
    organization: "American Association of Bovine Practitioners",
    amount: 2500,
    deadline_month: "October",
    renewable: false,
    type: "field-of-study",
    gpa_required: 2.5,
    essay_required: true,
    state: "National",
    year_eligible: "Undergraduate",
    description: "For students enrolled in an accredited school of veterinary medicine who demonstrate an interest in food animal veterinary practice.",
    url: "https://www.aabp.org/Foundation/Education/scholarships.asp",
    tags: ["veterinary", "agriculture", "food-animal", "rural"],
    likelihood: "high"
  },
  {
    id: 40,
    name: "American Political Science Association Minority Fellows Program",
    organization: "American Political Science Association",
    amount: 4000,
    deadline_month: "October",
    renewable: false,
    type: "field-of-study",
    gpa_required: 3.0,
    essay_required: true,
    state: "National",
    year_eligible: "Undergraduate",
    description: "Supports members of underrepresented minority groups who are in their first or second year of PhD programs in political science.",
    url: "https://www.apsanet.org/mfp",
    tags: ["political-science", "minority", "PhD", "social-sciences"],
    likelihood: "medium"
  },

  // ─────────────────────────────────────────────────────────────
  // ARTS & HUMANITIES SCHOLARSHIPS
  // ─────────────────────────────────────────────────────────────
  {
    id: 41,
    name: "YoungArts Foundation Award",
    organization: "National YoungArts Foundation",
    amount: 10000,
    deadline_month: "October",
    renewable: false,
    type: "arts",
    gpa_required: 0,
    essay_required: false,
    state: "National",
    year_eligible: "High School Senior",
    description: "For young artists (ages 15-18) in dance, music, theater, visual arts, and writing. Awards up to $10,000; finalists attend a week-long arts program and are nominated for Presidential Scholar in the Arts.",
    url: "https://youngarts.org",
    tags: ["arts", "music", "theater", "visual-arts", "writing", "dance"],
    likelihood: "medium"
  },
  {
    id: 42,
    name: "Scholastic Art & Writing Awards",
    organization: "Alliance for Young Artists & Writers",
    amount: 10000,
    deadline_month: "December",
    renewable: false,
    type: "arts",
    gpa_required: 0,
    essay_required: false,
    state: "National",
    year_eligible: "High School Senior",
    description: "The most prestigious recognition program for young creative writers and artists in grades 7-12. Gold Medal winners receive scholarship opportunities. Portfolio-based.",
    url: "https://www.artandwriting.org",
    tags: ["writing", "visual-arts", "creative", "portfolio", "high-school"],
    likelihood: "medium"
  },
  {
    id: 43,
    name: "Ayn Rand Institute Essay Contest",
    organization: "Ayn Rand Institute",
    amount: 10000,
    deadline_month: "April",
    renewable: false,
    type: "essay",
    gpa_required: 0,
    essay_required: true,
    state: "National",
    year_eligible: "High School Senior",
    description: "Annual essay contest on Ayn Rand's novels (separate contests for Anthem, The Fountainhead, and Atlas Shrugged). First prize $10,000; hundreds of smaller prizes.",
    url: "https://www.aynrand.org/students/essay-contests",
    tags: ["essay", "writing", "philosophy", "literature"],
    likelihood: "high"
  },
  {
    id: 44,
    name: "National Council of Teachers of English Achievement Award",
    organization: "National Council of Teachers of English",
    amount: 1500,
    deadline_month: "December",
    renewable: false,
    type: "arts",
    gpa_required: 0,
    essay_required: false,
    state: "National",
    year_eligible: "High School Senior",
    description: "Recognizes high school juniors who demonstrate exceptional ability in the use of the English language — both written and oral. Portfolio-based recognition.",
    url: "https://ncte.org/awards/achievement-awards-in-writing/",
    tags: ["writing", "english", "literature", "creative-writing"],
    likelihood: "medium"
  },
  {
    id: 45,
    name: "American Institute of Architecture Students Scholarship",
    organization: "American Institute of Architecture Students (AIAS)",
    amount: 5000,
    deadline_month: "March",
    renewable: false,
    type: "arts",
    gpa_required: 3.0,
    essay_required: true,
    state: "National",
    year_eligible: "Undergraduate",
    description: "For architecture students who demonstrate academic achievement, leadership, and service to the profession. Multiple scholarships available at different award levels.",
    url: "https://www.aias.org/programs/scholarships/",
    tags: ["architecture", "design", "leadership", "service"],
    likelihood: "medium"
  },

  // ─────────────────────────────────────────────────────────────
  // COMMUNITY SERVICE & LEADERSHIP SCHOLARSHIPS
  // ─────────────────────────────────────────────────────────────
  {
    id: 46,
    name: "Prudential Spirit of Community Awards",
    organization: "Prudential Financial",
    amount: 5000,
    deadline_month: "November",
    renewable: false,
    type: "community-service",
    gpa_required: 0,
    essay_required: true,
    state: "National",
    year_eligible: "High School Senior",
    description: "Honors middle and high school students for outstanding volunteer service to their communities. Top national honorees receive $5,000; state honorees receive $1,000.",
    url: "https://spirit.prudential.com",
    tags: ["community-service", "volunteer", "leadership", "youth"],
    likelihood: "medium"
  },
  {
    id: 47,
    name: "Prudential Emerging Visionaries",
    organization: "Prudential Financial / Ashoka",
    amount: 15000,
    deadline_month: "November",
    renewable: false,
    type: "community-service",
    gpa_required: 0,
    essay_required: true,
    state: "National",
    year_eligible: "High School Senior",
    description: "For young people (ages 14-18) with innovative solutions to financial or social challenges. 25 winners receive $5,000; one Financial Solutions grand prize winner receives an additional $10,000.",
    url: "https://www.changemakers.com/en/challenge/emergingvisionaries",
    tags: ["social-innovation", "entrepreneurship", "community-service", "youth"],
    likelihood: "low"
  },
  {
    id: 48,
    name: "DoSomething.org Scholarships",
    organization: "DoSomething.org",
    amount: 5000,
    deadline_month: "Rolling",
    renewable: false,
    type: "community-service",
    gpa_required: 0,
    essay_required: false,
    state: "National",
    year_eligible: "Any",
    description: "Runs multiple campaigns throughout the year with no essays required. Students earn scholarships by taking action on social causes. Open to ages 13-25.",
    url: "https://www.dosomething.org/us/scholarships",
    tags: ["community-service", "volunteer", "social-change", "no-essay"],
    likelihood: "high"
  },
  {
    id: 49,
    name: "Presidential Freedom Scholarship",
    organization: "American Association of School Administrators",
    amount: 1000,
    deadline_month: "Rolling",
    renewable: false,
    type: "community-service",
    gpa_required: 0,
    essay_required: true,
    state: "National",
    year_eligible: "High School Senior",
    description: "For students who demonstrate an outstanding commitment to community service and civic responsibility. Nominated by their school principal.",
    url: "https://www.aasa.org/content/presidential-freedom-scholarship",
    tags: ["civic", "community-service", "freedom", "volunteer"],
    likelihood: "medium"
  },
  {
    id: 50,
    name: "Rotary Club Local Scholarship",
    organization: "Rotary International (local clubs)",
    amount: 3000,
    deadline_month: "Rolling",
    renewable: false,
    type: "community-service",
    gpa_required: 0,
    essay_required: true,
    state: "National",
    year_eligible: "Any",
    description: "Many local Rotary clubs offer scholarships. Amounts and requirements vary by club. Contact your local Rotary club directly to find out about opportunities in your area.",
    url: "https://www.rotary.org/en/our-programs/scholarships",
    tags: ["community-service", "local", "leadership", "civic"],
    likelihood: "high"
  },

  // ─────────────────────────────────────────────────────────────
  // FIRST-GENERATION & NEED-BASED
  // ─────────────────────────────────────────────────────────────
  {
    id: 51,
    name: "Federal Pell Grant",
    organization: "US Department of Education",
    amount: 7395,
    deadline_month: "June",
    renewable: true,
    type: "need-based",
    gpa_required: 0,
    essay_required: false,
    state: "National",
    year_eligible: "Undergraduate",
    description: "The foundation of federal financial aid for low-income undergraduate students. Maximum award for 2024-25 is $7,395/year. Apply via FAFSA; automatically awarded if eligible.",
    url: "https://studentaid.gov/understand-aid/types/grants/pell",
    tags: ["FAFSA", "need-based", "federal", "renewable", "low-income"],
    likelihood: "high"
  },
  {
    id: 52,
    name: "First in the Family Scholarship",
    organization: "Scholarship America / Dollars for Scholars",
    amount: 1000,
    deadline_month: "Rolling",
    renewable: false,
    type: "need-based",
    gpa_required: 0,
    essay_required: true,
    state: "National",
    year_eligible: "Any",
    description: "For students who are the first in their family to attend college. Available through local Dollars for Scholars chapters. Amounts and eligibility vary by chapter.",
    url: "https://scholarshipamerica.org",
    tags: ["first-generation", "need-based", "local", "family"],
    likelihood: "high"
  },
  {
    id: 53,
    name: "Imagine America Foundation Scholarship",
    organization: "Imagine America Foundation",
    amount: 1000,
    deadline_month: "Rolling",
    renewable: false,
    type: "need-based",
    gpa_required: 0,
    essay_required: false,
    state: "National",
    year_eligible: "High School Senior",
    description: "For high school seniors planning to attend an eligible career college or university. Open to students with a 2.5 GPA and who meet financial need requirements.",
    url: "https://www.imagine-america.org",
    tags: ["career-college", "vocational", "need-based"],
    likelihood: "high"
  },
  {
    id: 54,
    name: "Sallie Mae Scholarship",
    organization: "Sallie Mae",
    amount: 2000,
    deadline_month: "Rolling",
    renewable: false,
    type: "need-based",
    gpa_required: 0,
    essay_required: true,
    state: "National",
    year_eligible: "Any",
    description: "Multiple scholarships available throughout the year for undergraduate and graduate students with varying criteria. Open to all fields of study.",
    url: "https://www.salliemae.com/college-planning/scholarships/",
    tags: ["need-based", "any-major", "undergraduate", "no-restrictions"],
    likelihood: "high"
  },

  // ─────────────────────────────────────────────────────────────
  // REGIONAL / STATE SCHOLARSHIPS
  // ─────────────────────────────────────────────────────────────
  {
    id: 55,
    name: "California Dream Act Scholarship (Cal Grant)",
    organization: "California Student Aid Commission",
    amount: 12630,
    deadline_month: "March",
    renewable: true,
    type: "regional",
    gpa_required: 2.0,
    essay_required: false,
    state: "California",
    year_eligible: "High School Senior",
    description: "California's main state grant program. Cal Grant A covers tuition at UC and CSU schools; Cal Grant B provides a living allowance for community college. Renewable for 4 years.",
    url: "https://www.csac.ca.gov/cal-grants",
    tags: ["California", "state-grant", "need-based", "renewable", "FAFSA"],
    likelihood: "high"
  },
  {
    id: 56,
    name: "Texas Public Education Grant (TPEG)",
    organization: "Texas Higher Education Coordinating Board",
    amount: 5000,
    deadline_month: "Rolling",
    renewable: true,
    type: "regional",
    gpa_required: 0,
    essay_required: false,
    state: "Texas",
    year_eligible: "Any",
    description: "Need-based grant for Texas residents attending public Texas colleges and universities. Award amounts vary by institution and are based on financial need via FAFSA.",
    url: "https://www.highered.texas.gov/student-success/paying-for-college/financial-aid-programs/tpeg/",
    tags: ["Texas", "state-grant", "need-based", "renewable", "public-university"],
    likelihood: "high"
  },
  {
    id: 57,
    name: "New York State Tuition Assistance Program (TAP)",
    organization: "New York State Higher Education Services Corporation",
    amount: 5165,
    deadline_month: "Rolling",
    renewable: true,
    type: "regional",
    gpa_required: 0,
    essay_required: false,
    state: "New York",
    year_eligible: "Any",
    description: "Annual grant for New York residents attending in-state colleges. Award amounts are based on family income and enrollment status. Apply via FAFSA + TAP application.",
    url: "https://www.hesc.ny.gov/pay-for-college/financial-aid/types-of-financial-aid/nys-grants-scholarships-awards/tap.html",
    tags: ["New York", "state-grant", "need-based", "renewable", "in-state"],
    likelihood: "high"
  },
  {
    id: 58,
    name: "Florida Student Assistance Grant (FSAG)",
    organization: "Florida Department of Education, Office of Student Financial Assistance",
    amount: 2710,
    deadline_month: "April",
    renewable: true,
    type: "regional",
    gpa_required: 0,
    essay_required: false,
    state: "Florida",
    year_eligible: "Any",
    description: "Need-based grant for Florida residents attending eligible Florida public and private institutions. Award amounts depend on financial need and available funds.",
    url: "https://www.floridastudentfinancialplanningportal.gov",
    tags: ["Florida", "state-grant", "need-based", "renewable", "FAFSA"],
    likelihood: "high"
  },
  {
    id: 59,
    name: "Illinois Monetary Award Program (MAP)",
    organization: "Illinois Student Assistance Commission",
    amount: 5340,
    deadline_month: "October",
    renewable: true,
    type: "regional",
    gpa_required: 0,
    essay_required: false,
    state: "Illinois",
    year_eligible: "Any",
    description: "Illinois's largest grant program for undergraduate students. Funds are limited and allocated on a first-come, first-served basis to FAFSA applicants with financial need.",
    url: "https://www.isac.org/students/during-college/types-of-aid/monetary-award-program/",
    tags: ["Illinois", "state-grant", "need-based", "renewable", "FAFSA"],
    likelihood: "high"
  },
  {
    id: 60,
    name: "Washington State Need Grant",
    organization: "Washington Student Achievement Council",
    amount: 11082,
    deadline_month: "Rolling",
    renewable: true,
    type: "regional",
    gpa_required: 0,
    essay_required: false,
    state: "Washington",
    year_eligible: "Any",
    description: "Washington's primary need-based financial aid program for low- and middle-income students attending eligible Washington institutions. Awards based on FAFSA information.",
    url: "https://wsac.wa.gov/need-grant",
    tags: ["Washington", "state-grant", "need-based", "renewable", "FAFSA"],
    likelihood: "high"
  },
  {
    id: 61,
    name: "Georgia HOPE Scholarship",
    organization: "Georgia Student Finance Commission",
    amount: 6300,
    deadline_month: "Rolling",
    renewable: true,
    type: "regional",
    gpa_required: 3.0,
    essay_required: false,
    state: "Georgia",
    year_eligible: "High School Senior",
    description: "For Georgia high school graduates with a 3.0 GPA attending eligible Georgia colleges. Funded by the Georgia Lottery. Renewable as long as GPA is maintained.",
    url: "https://www.gacollege411.org/Financial_Aid_Planning/GSFA/Default.aspx",
    tags: ["Georgia", "merit", "renewable", "state-funded", "lottery"],
    likelihood: "high"
  },
  {
    id: 62,
    name: "Tennessee HOPE Scholarship",
    organization: "Tennessee Student Assistance Corporation",
    amount: 5500,
    deadline_month: "Rolling",
    renewable: true,
    type: "regional",
    gpa_required: 3.0,
    essay_required: false,
    state: "Tennessee",
    year_eligible: "High School Senior",
    description: "Merit-based scholarship for Tennessee high school graduates attending in-state colleges. Based on ACT/SAT scores and GPA. Renewable with academic progress requirements.",
    url: "https://www.tn.gov/collegepays/money-for-college/tn-education-lottery-scholarship-program/tennessee-hope-scholarship.html",
    tags: ["Tennessee", "merit", "renewable", "lottery", "test-scores"],
    likelihood: "high"
  },
  {
    id: 63,
    name: "Bright Futures Scholarship (Florida)",
    organization: "Florida Department of Education",
    amount: 3130,
    deadline_month: "Rolling",
    renewable: true,
    type: "regional",
    gpa_required: 3.5,
    essay_required: false,
    state: "Florida",
    year_eligible: "High School Senior",
    description: "Florida's merit-based scholarship program. Florida Academic Scholars receive 100% of tuition; Florida Medallion Scholars receive 75%. Based on GPA and test scores.",
    url: "https://www.floridastudentfinancialplanningportal.gov/SF/FBF",
    tags: ["Florida", "merit", "renewable", "test-scores", "academic"],
    likelihood: "high"
  },
  {
    id: 64,
    name: "Texas A&M University Scholarships",
    organization: "Texas A&M University",
    amount: 8000,
    deadline_month: "December",
    renewable: true,
    type: "regional",
    gpa_required: 3.5,
    essay_required: true,
    state: "Texas",
    year_eligible: "High School Senior",
    description: "Texas A&M offers numerous merit-based scholarships through the Scholarships & Financial Aid office for incoming freshmen. Award amounts vary widely.",
    url: "https://financialaid.tamu.edu/Scholarships",
    tags: ["Texas", "university", "merit", "renewable", "freshman"],
    likelihood: "medium"
  },
  {
    id: 65,
    name: "Ohio College Opportunity Grant (OCOG)",
    organization: "Ohio Department of Higher Education",
    amount: 4000,
    deadline_month: "October",
    renewable: true,
    type: "regional",
    gpa_required: 0,
    essay_required: false,
    state: "Ohio",
    year_eligible: "Any",
    description: "Need-based grant for Ohio residents with low family incomes attending eligible Ohio public and private colleges. Based on FAFSA financial need information.",
    url: "https://highered.ohio.gov/students-families/student-funding/ocog",
    tags: ["Ohio", "state-grant", "need-based", "renewable", "FAFSA"],
    likelihood: "high"
  },

  // ─────────────────────────────────────────────────────────────
  // ESSAY COMPETITIONS
  // ─────────────────────────────────────────────────────────────
  {
    id: 66,
    name: "Scholarship Zone Essay Scholarship",
    organization: "Scholarship Zone",
    amount: 1500,
    deadline_month: "Rolling",
    renewable: false,
    type: "essay",
    gpa_required: 0,
    essay_required: true,
    state: "National",
    year_eligible: "Any",
    description: "Monthly essay scholarships for students of all ages. Topics change monthly. Open to all fields of study with varying prompts about career goals and personal experiences.",
    url: "https://www.scholarshipzone.com",
    tags: ["essay", "monthly", "any-major", "writing"],
    likelihood: "high"
  },
  {
    id: 67,
    name: "Voice of Democracy Audio Essay Competition",
    organization: "Veterans of Foreign Wars (VFW)",
    amount: 30000,
    deadline_month: "October",
    renewable: false,
    type: "essay",
    gpa_required: 0,
    essay_required: true,
    state: "National",
    year_eligible: "High School Senior",
    description: "Audio essay competition for students in grades 9-12. Theme changes each year. State winners each receive at least $1,000; national scholarship awarded at VFW national convention.",
    url: "https://www.vfw.org/community/youth-and-education/youth-scholarships",
    tags: ["patriotic", "essay", "veterans", "audio", "civic"],
    likelihood: "medium"
  },
  {
    id: 68,
    name: "Patriot's Pen Youth Essay Contest",
    organization: "Veterans of Foreign Wars (VFW)",
    amount: 5000,
    deadline_month: "October",
    renewable: false,
    type: "essay",
    gpa_required: 0,
    essay_required: true,
    state: "National",
    year_eligible: "High School Senior",
    description: "Essay contest for students in grades 6-8 on a patriotic theme. National first-place winner receives $5,000; all entrants receive ribbons. Multiple levels of competition.",
    url: "https://www.vfw.org/community/youth-and-education/youth-scholarships",
    tags: ["patriotic", "essay", "civics", "veterans"],
    likelihood: "medium"
  },
  {
    id: 69,
    name: "Create-A-Greeting-Card Scholarship",
    organization: "Galison/Mudpuppy",
    amount: 10000,
    deadline_month: "February",
    renewable: false,
    type: "essay",
    gpa_required: 0,
    essay_required: false,
    state: "National",
    year_eligible: "Any",
    description: "Design a greeting card for the chance to win $10,000. No essay required — submit original artwork. Open to students of any age currently enrolled.",
    url: "https://www.galison.com/pages/scholarship",
    tags: ["art", "design", "no-essay", "creative", "competition"],
    likelihood: "high"
  },
  {
    id: 70,
    name: "Davidson Fellows Scholarship",
    organization: "Davidson Institute",
    amount: 50000,
    deadline_month: "February",
    renewable: false,
    type: "merit",
    gpa_required: 0,
    essay_required: true,
    state: "National",
    year_eligible: "High School Senior",
    description: "For profoundly gifted students under 18 who complete a significant piece of work in science, technology, mathematics, music, literature, or philosophy.",
    url: "https://www.davidsongifted.org/gifted-programs/fellows-scholarship/",
    tags: ["gifted", "research", "STEM", "arts", "outstanding-project"],
    likelihood: "low"
  },

  // ─────────────────────────────────────────────────────────────
  // ATHLETICS SCHOLARSHIPS
  // ─────────────────────────────────────────────────────────────
  {
    id: 71,
    name: "NAIA Athletics Scholarship",
    organization: "National Association of Intercollegiate Athletics (NAIA)",
    amount: 15000,
    deadline_month: "Rolling",
    renewable: true,
    type: "athletic",
    gpa_required: 2.0,
    essay_required: false,
    state: "National",
    year_eligible: "High School Senior",
    description: "Athletics-based scholarships at NAIA member institutions in 27 sports. Often more accessible than NCAA D1 scholarships. Contact coaches directly at NAIA schools.",
    url: "https://www.naia.org/scholarships",
    tags: ["athletics", "sports", "renewable", "college-sports"],
    likelihood: "medium"
  },
  {
    id: 72,
    name: "US Tennis Association (USTA) Scholarship",
    organization: "US Tennis Association Foundation",
    amount: 6000,
    deadline_month: "February",
    renewable: false,
    type: "athletic",
    gpa_required: 3.0,
    essay_required: true,
    state: "National",
    year_eligible: "High School Senior",
    description: "For students who have participated in a USTA League or USTA/ITA Collegiate program and show academic achievement and financial need.",
    url: "https://www.ustafoundation.com/scholarships",
    tags: ["tennis", "athletics", "sports", "need-based"],
    likelihood: "medium"
  },

  // ─────────────────────────────────────────────────────────────
  // ADDITIONAL NATIONAL SCHOLARSHIPS
  // ─────────────────────────────────────────────────────────────
  {
    id: 73,
    name: "Tylenol Future Care Scholarship",
    organization: "Johnson & Johnson / Tylenol",
    amount: 10000,
    deadline_month: "June",
    renewable: false,
    type: "field-of-study",
    gpa_required: 3.0,
    essay_required: true,
    state: "National",
    year_eligible: "Any",
    description: "For students committed to a career in healthcare — including medicine, nursing, dentistry, pharmacy, and public health. Awards ranging from $5,000 to $10,000.",
    url: "https://www.tylenol.com/news/scholarship",
    tags: ["healthcare", "medicine", "nursing", "pharmacy", "dentistry"],
    likelihood: "medium"
  },
  {
    id: 74,
    name: "Gen and Kelly Tanabe Scholarship",
    organization: "Gen and Kelly Tanabe",
    amount: 1000,
    deadline_month: "July",
    renewable: false,
    type: "merit",
    gpa_required: 0,
    essay_required: true,
    state: "National",
    year_eligible: "Any",
    description: "Open to all high school, college, and graduate students. Essay required. No minimum GPA. Three deadline periods per year (January, April, July).",
    url: "https://www.genkellyscholarship.com",
    tags: ["essay", "any-major", "any-year", "accessible"],
    likelihood: "high"
  },
  {
    id: 75,
    name: "Fastweb Scholarship",
    organization: "Fastweb",
    amount: 1000,
    deadline_month: "Rolling",
    renewable: false,
    type: "merit",
    gpa_required: 0,
    essay_required: false,
    state: "National",
    year_eligible: "Any",
    description: "Fastweb's own scholarship sweepstakes. Open to all students 13+. No essay required. Simply create a Fastweb account and complete your profile to enter.",
    url: "https://www.fastweb.com/college-scholarships/articles/the-fastweb-scholarship",
    tags: ["no-essay", "sweepstakes", "accessible", "any-major", "any-year"],
    likelihood: "high"
  },
  {
    id: 76,
    name: "Niche $25,000 Scholarship",
    organization: "Niche.com",
    amount: 25000,
    deadline_month: "Rolling",
    renewable: false,
    type: "merit",
    gpa_required: 0,
    essay_required: false,
    state: "National",
    year_eligible: "Any",
    description: "A monthly sweepstakes-style scholarship requiring only a brief application. No essay required. Open to students and parents of students planning to attend college.",
    url: "https://www.niche.com/colleges/scholarships/",
    tags: ["no-essay", "sweepstakes", "any-year", "any-major", "accessible"],
    likelihood: "high"
  },
  {
    id: 77,
    name: "Society of Professional Journalists Scholarship",
    organization: "Society of Professional Journalists",
    organization: "Society of Professional Journalists (SPJ)",
    amount: 3000,
    deadline_month: "April",
    renewable: false,
    type: "field-of-study",
    gpa_required: 3.0,
    essay_required: true,
    state: "National",
    year_eligible: "Undergraduate",
    description: "For journalism students with demonstrated ability and commitment to the field. Multiple award levels. Students must join or be eligible for SPJ student chapter membership.",
    url: "https://www.spj.org/scholarships.asp",
    tags: ["journalism", "media", "reporting", "writing"],
    likelihood: "medium"
  },
  {
    id: 78,
    name: "Lamb Weston Scholarship",
    organization: "Lamb Weston",
    amount: 3000,
    deadline_month: "March",
    renewable: false,
    type: "regional",
    gpa_required: 2.5,
    essay_required: true,
    state: "Washington",
    year_eligible: "High School Senior",
    description: "For students in potato-producing communities (WA, OR, ID) planning to study agriculture, food science, engineering, or business at a 2- or 4-year institution.",
    url: "https://www.lambweston.com/giving-back",
    tags: ["agriculture", "food-science", "Pacific-Northwest", "regional"],
    likelihood: "high"
  },
  {
    id: 79,
    name: "American Legion Oratorical Contest",
    organization: "American Legion",
    amount: 25000,
    deadline_month: "Rolling",
    renewable: false,
    type: "community-service",
    gpa_required: 0,
    essay_required: true,
    state: "National",
    year_eligible: "High School Senior",
    description: "Public speaking contest for high school students on US Constitutional topics. National champion receives $25,000; state champions receive $1,500; excellent odds at the local level.",
    url: "https://www.legion.org/oratorical",
    tags: ["speech", "constitutional", "veterans", "civic", "public-speaking"],
    likelihood: "medium"
  },
  {
    id: 80,
    name: "AFSA High School Scholarship Contest",
    organization: "American Foreign Service Association (AFSA)",
    amount: 2500,
    deadline_month: "February",
    renewable: false,
    type: "essay",
    gpa_required: 0,
    essay_required: true,
    state: "National",
    year_eligible: "High School Senior",
    description: "Essay contest for high school students on topics related to US foreign policy and international affairs. First prize: $2,500; second: $1,250; third: $750.",
    url: "https://afsa.org/student-programs/high-school-essay-contest",
    tags: ["essay", "foreign-policy", "international", "civics"],
    likelihood: "high"
  },
  {
    id: 81,
    name: "Soroptimist Live Your Dream Award",
    organization: "Soroptimist International of the Americas",
    amount: 16000,
    deadline_month: "November",
    renewable: false,
    type: "identity",
    gpa_required: 0,
    essay_required: true,
    state: "National",
    year_eligible: "Undergraduate",
    description: "For women who provide the primary financial support for themselves and their dependents. Supports women returning to school. Top award: $16,000; club-level awards: $500–$1,500.",
    url: "https://www.soroptimist.org/awards/live-your-dream-awards.html",
    tags: ["women", "non-traditional", "adult-learner", "need-based", "caregiver"],
    likelihood: "medium"
  },
  {
    id: 82,
    name: "Jackie Robinson Foundation Scholarship",
    organization: "Jackie Robinson Foundation",
    amount: 40000,
    deadline_month: "February",
    renewable: true,
    type: "identity",
    gpa_required: 0,
    essay_required: true,
    state: "National",
    year_eligible: "High School Senior",
    description: "For minority students who demonstrate extraordinary character, leadership potential, and financial need. $10,000/year for 4 years plus mentoring, networking, and internship opportunities.",
    url: "https://jackierobinson.org/apply/",
    tags: ["minority", "leadership", "renewable", "mentorship", "need-based"],
    likelihood: "low"
  },
  {
    id: 83,
    name: "Truman Scholarship",
    organization: "Harry S. Truman Scholarship Foundation",
    amount: 30000,
    deadline_month: "February",
    renewable: false,
    type: "merit",
    gpa_required: 3.0,
    essay_required: true,
    state: "National",
    year_eligible: "Undergraduate",
    description: "Prestigious scholarship for college juniors committed to careers in public service and government. Requires college nomination. $30,000 for graduate school.",
    url: "https://www.truman.gov",
    tags: ["public-service", "government", "leadership", "graduate-school", "prestigious"],
    likelihood: "low"
  },
  {
    id: 84,
    name: "AXA Achievement Scholarship",
    organization: "AXA Foundation",
    amount: 25000,
    deadline_month: "December",
    renewable: false,
    type: "merit",
    gpa_required: 0,
    essay_required: true,
    state: "National",
    year_eligible: "High School Senior",
    description: "For students who demonstrate outstanding achievement in school, community, or work experience. 52 scholarships awarded: $25,000 for national and $10,000 for state winners.",
    url: "https://us.axa.com/axa-foundation/scholarship.html",
    tags: ["achievement", "leadership", "community", "merit"],
    likelihood: "medium"
  },
  {
    id: 85,
    name: "Foot Locker Scholar Athletes",
    organization: "Foot Locker Foundation",
    amount: 20000,
    deadline_month: "January",
    renewable: false,
    type: "athletic",
    gpa_required: 3.0,
    essay_required: true,
    state: "National",
    year_eligible: "High School Senior",
    description: "For student athletes who demonstrate academic excellence, financial need, and leadership both on and off the field. $5,000/year for 4 years.",
    url: "https://footlockerscholarathletes.com",
    tags: ["athletics", "sports", "leadership", "need-based", "renewable"],
    likelihood: "medium"
  },
  {
    id: 86,
    name: "Greenhouse Scholars Program",
    organization: "Greenhouse Scholars",
    amount: 40000,
    deadline_month: "December",
    renewable: true,
    type: "need-based",
    gpa_required: 3.0,
    essay_required: true,
    state: "National",
    year_eligible: "High School Senior",
    description: "Holistic 4-year support program (up to $10,000/yr) for high-potential, low-income students who are the first in their family to attend college. Includes mentorship and community.",
    url: "https://greenhousescholars.org",
    tags: ["first-generation", "low-income", "renewable", "mentorship", "leadership"],
    likelihood: "medium"
  },
  {
    id: 87,
    name: "Newman Civic Fellowship",
    organization: "Campus Compact",
    amount: 1000,
    deadline_month: "February",
    renewable: false,
    type: "community-service",
    gpa_required: 0,
    essay_required: true,
    state: "National",
    year_eligible: "Undergraduate",
    description: "Annual award recognizing inspiring college students who are creating meaningful change in their communities through civic engagement and service.",
    url: "https://compact.org/newman-civic-fellowship",
    tags: ["civic", "community-service", "leadership", "nominated"],
    likelihood: "medium"
  },
  {
    id: 88,
    name: "Chick-fil-A Leadership Scholarship",
    organization: "Chick-fil-A",
    amount: 2500,
    deadline_month: "March",
    renewable: false,
    type: "merit",
    gpa_required: 2.5,
    essay_required: true,
    state: "National",
    year_eligible: "High School Senior",
    description: "For Chick-fil-A restaurant employees who plan to continue their education. Over $19 million has been awarded since 1973. Available to both full- and part-time Team Members.",
    url: "https://www.chick-fil-a.com/stories/community/chick-fil-a-leadership-scholarship",
    tags: ["employee", "leadership", "work-experience", "merit"],
    likelihood: "high"
  },
  {
    id: 89,
    name: "Student Veterans of America Scholarship",
    organization: "Student Veterans of America (SVA)",
    amount: 5000,
    deadline_month: "February",
    renewable: false,
    type: "identity",
    gpa_required: 2.5,
    essay_required: true,
    state: "National",
    year_eligible: "Undergraduate",
    description: "For military veterans who are currently enrolled in an undergraduate degree program at an SVA chapter institution. Multiple awards given annually.",
    url: "https://studentveterans.org/programs/scholarships/",
    tags: ["veterans", "military", "undergraduate"],
    likelihood: "medium"
  },
  {
    id: 90,
    name: "American Welding Society Scholarship",
    organization: "American Welding Society",
    amount: 5000,
    deadline_month: "February",
    renewable: false,
    type: "field-of-study",
    gpa_required: 2.5,
    essay_required: true,
    state: "National",
    year_eligible: "Any",
    description: "For students pursuing careers in welding engineering, welding technology, or welding-related fields. AWS awards over $1M in scholarships annually to students at all levels.",
    url: "https://www.aws.org/foundation/page/scholarships",
    tags: ["welding", "vocational", "engineering", "trade", "manufacturing"],
    likelihood: "medium"
  },
  {
    id: 91,
    name: "Alpha Kappa Alpha Educational Advancement Foundation Scholarship",
    organization: "Alpha Kappa Alpha Sorority",
    amount: 1000,
    deadline_month: "January",
    renewable: false,
    type: "identity",
    gpa_required: 2.5,
    essay_required: true,
    state: "National",
    year_eligible: "Any",
    description: "For students in academic need who demonstrate leadership through civic and community involvement. Open to any student; preference given to AKA members and their families.",
    url: "https://akaeaf.org/scholarships",
    tags: ["community-service", "leadership", "African-American", "need-based"],
    likelihood: "medium"
  },
  {
    id: 92,
    name: "Environmental Science and Conservation Fellowship",
    organization: "Doris Duke Conservation Scholars Program",
    amount: 15000,
    deadline_month: "January",
    renewable: false,
    type: "field-of-study",
    gpa_required: 3.0,
    essay_required: true,
    state: "National",
    year_eligible: "Undergraduate",
    description: "For underrepresented students in environmental science and conservation. Paid internship ($7,500) plus housing, travel, and mentoring. Program is housed at 6 universities.",
    url: "https://dorisduke.org",
    tags: ["environment", "conservation", "minority", "internship", "science"],
    likelihood: "medium"
  },
  {
    id: 93,
    name: "Harry S. Truman Scholarship",
    organization: "Truman Scholarship Foundation",
    amount: 30000,
    deadline_month: "February",
    renewable: false,
    type: "merit",
    gpa_required: 3.0,
    essay_required: true,
    state: "National",
    year_eligible: "Undergraduate",
    description: "For college juniors committed to public service careers in government or the nonprofit sector. Highly selective; requires college nomination. Covers up to $30,000 for graduate school.",
    url: "https://www.truman.gov",
    tags: ["public-service", "government", "leadership", "graduate"],
    likelihood: "low"
  },
  {
    id: 94,
    name: "John F. Kennedy Profile in Courage Essay Contest",
    organization: "JFK Library Foundation",
    amount: 10000,
    deadline_month: "January",
    renewable: false,
    type: "essay",
    gpa_required: 0,
    essay_required: true,
    state: "National",
    year_eligible: "High School Senior",
    description: "For high school students in grades 9-12 who write a persuasive essay about an act of political courage by a US elected official, past or present.",
    url: "https://www.jfklibrary.org/events-and-awards/profile-in-courage-award/essay-contest",
    tags: ["essay", "history", "politics", "civics", "writing"],
    likelihood: "medium"
  },
  {
    id: 95,
    name: "Gloria Barron Prize for Young Heroes",
    organization: "The Barron Prize",
    amount: 10000,
    deadline_month: "April",
    renewable: false,
    type: "community-service",
    gpa_required: 0,
    essay_required: true,
    state: "National",
    year_eligible: "High School Senior",
    description: "Honors outstanding young people (ages 8-18) who have made a significant positive difference to people and the planet. 25 winners per year receive $10,000 each.",
    url: "https://barronprize.org",
    tags: ["youth-leadership", "environment", "social-change", "community-service"],
    likelihood: "medium"
  },
  {
    id: 96,
    name: "Scholarship America Dream Award",
    organization: "Scholarship America",
    amount: 5000,
    deadline_month: "March",
    renewable: false,
    type: "need-based",
    gpa_required: 3.0,
    essay_required: true,
    state: "National",
    year_eligible: "Undergraduate",
    description: "For students who are in their sophomore, junior, or senior year of college and have maintained academic excellence despite significant personal challenges.",
    url: "https://scholarshipamerica.org/dream-award/",
    tags: ["resilience", "adversity", "need-based", "perseverance"],
    likelihood: "medium"
  },
  {
    id: 97,
    name: "Annie's Homegrown Sustainable Agriculture Scholarship",
    organization: "Annie's Homegrown",
    amount: 10000,
    deadline_month: "March",
    renewable: false,
    type: "field-of-study",
    gpa_required: 3.0,
    essay_required: true,
    state: "National",
    year_eligible: "Undergraduate",
    description: "For students pursuing studies in sustainable agriculture, food systems, or environmental science. Community service and leadership in food sustainability are highly valued.",
    url: "https://www.annies.com/sustainability/grants-and-scholarships/",
    tags: ["agriculture", "sustainability", "food-systems", "environment"],
    likelihood: "medium"
  },
  {
    id: 98,
    name: "Target All-Around Scholarship",
    organization: "Target Corporation",
    amount: 10000,
    deadline_month: "April",
    renewable: true,
    type: "merit",
    gpa_required: 2.5,
    essay_required: true,
    state: "National",
    year_eligible: "High School Senior",
    description: "Awarded to seniors who demonstrate an excellent balance of academics, community service, leadership, and work experience. $10,000 scholarships awarded nationally.",
    url: "https://corporate.target.com/social-responsibility/education",
    tags: ["leadership", "community-service", "work-experience", "merit"],
    likelihood: "medium"
  },
  {
    id: 99,
    name: "Walmart Associate Scholarship",
    organization: "Walmart Foundation",
    amount: 16000,
    deadline_month: "January",
    renewable: true,
    type: "merit",
    gpa_required: 2.5,
    essay_required: true,
    state: "National",
    year_eligible: "Any",
    description: "For Walmart and Sam's Club associates and their family members. Part-time and full-time associates, their spouses, and their dependents are eligible. Up to $16,000 total.",
    url: "https://giving.walmart.com/walmart-foundation/associate-scholarships",
    tags: ["employee", "retail", "merit", "renewable", "family"],
    likelihood: "high"
  },
  {
    id: 100,
    name: "Benjamin A. Gilman International Scholarship",
    organization: "US Department of State",
    amount: 5000,
    deadline_month: "March",
    renewable: false,
    type: "need-based",
    gpa_required: 0,
    essay_required: true,
    state: "National",
    year_eligible: "Undergraduate",
    description: "For Pell Grant recipients studying or interning abroad. Expands participation in study abroad to students with financial need and from underrepresented backgrounds.",
    url: "https://www.gilmanscholarship.org",
    tags: ["study-abroad", "international", "need-based", "Pell-Grant", "travel"],
    likelihood: "medium"
  }
];
